export const produto = [
    {
      id: 1,
      name: 'Tênis Nike Revolution 6 Next Nature Masculino',
      category: 'Casual | Nike | REF:38416711',
      rating: 4,
      reviews: 90,
      price: 219.0,
      originalPrice: 350.0,
      installment: 1789.99,
      description: 'O Tênis Masculino Nike Revolution 6 Next Nature revisita o original icônico com linhas de design modernas e amortecimento super leve. O amortecimento Air-Sole revolucionário da Nike foi introduzido nos calçados Nike em 1978.',
      sizes: [39, 40, 41, 42, 43],
      colors: ['#3498db', '#2ecc71', '#e74c3c', '#f39c12', '#9b59b6'],
      img: 'https://m.media-amazon.com/images/I/71ARX0SJ4rL._AC_SY695_.jpg',
      thumbnails: ['', '', '', '']
    },
    {
      id: 2,
      name: 'Camisa Nike Dri-FIT Masculina',
      category: 'Esportiva | Nike | REF:23456789',
      rating: 5,
      reviews: 120,
      price: 159.0,
      originalPrice: 250.0,
      installment: 1329.99,
      description: 'A Camisa Nike Dri-FIT oferece conforto e tecnologia para treinos intensos. Feita com tecido que absorve o suor e mantém você seco, ideal para atividades físicas.',
      sizes: ['P', 'M', 'G', 'GG'],
      colors: ['#ff5733', '#33ff57', '#3357ff', '#f4c542', '#a142f4'],
      img: 'https://m.media-amazon.com/images/I/611KgyJXPzL._AC_SY695_.jpg',
      thumbnails: ['', '', '', '']
    },
    {
      id: 3,
      name: 'Tênis Adidas Ultraboost 22',
      category: 'Performance | Adidas | REF:34567890',
      rating: 4.5,
      reviews: 75,
      price: 349.0,
      originalPrice: 450.0,
      installment: 2929.99,
      description: 'O Tênis Adidas Ultraboost 22 é conhecido pelo seu conforto excepcional e responsividade. Ideal para corrida e treinos intensos, com tecnologia Boost para amortecimento.',
      sizes: [40, 41, 42, 43, 44],
      colors: ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd'],
      img: 'https://m.media-amazon.com/images/I/61MlssKgd-L._AC_SY695_.jpg',
      thumbnails: ['', '', '', '']
    },
    {
      id: 4,
      name: 'Camisa Puma Essentials',
      category: 'Casual | Puma | REF:45678901',
      rating: 4,
      reviews: 60,
      price: 129.0,
      originalPrice: 200.0,
      installment: 1099.99,
      description: 'A Camisa Puma Essentials é perfeita para o uso diário com estilo e conforto. Feita com algodão macio e com o logotipo Puma discreto.',
      sizes: ['P', 'M', 'G'],
      colors: ['#e5e5e5', '#000000', '#ff0050', '#008000', '#0000ff'],
      img: 'https://m.media-amazon.com/images/I/71qePDOt2sL._AC_SY695_.jpg',
      thumbnails: ['', '', '', '']
    },
    {
      id: 5,
      name: 'Tênis Reebok Classic Leather',
      category: 'Casual | Reebok | REF:56789012',
      rating: 4,
      reviews: 85,
      price: 289.0,
      originalPrice: 350.0,
      installment: 2509.99,
      description: 'O Tênis Reebok Classic Leather combina conforto e estilo. Feito com couro premium e solado de borracha para durabilidade e suporte.',
      sizes: [39, 40, 41, 42, 43],
      colors: ['#d62728', '#9467bd', '#8c564b', '#e377c2', '#7f7f7f'],
      img: 'https://m.media-amazon.com/images/I/61MlssKgd-L._AC_SY695_.jpg',
      thumbnails: ['', '', '', '']
    },
    {
      id: 6,
      name: 'Camisa Under Armour Tech',
      category: 'Esportiva | Under Armour | REF:67890123',
      rating: 4.5,
      reviews: 95,
      price: 179.0,
      originalPrice: 250.0,
      installment: 1499.99,
      description: 'A Camisa Under Armour Tech é ideal para atividades físicas com tecnologia que absorve o suor e proporciona uma sensação de frescor.',
      sizes: ['P', 'M', 'G', 'GG'],
      colors: ['#ffcc00', '#00ffcc', '#cc00ff', '#ff3300', '#3399ff'],
      img: 'https://m.media-amazon.com/images/I/71qePDOt2sL._AC_SY695_.jpg_.jpg',
      thumbnails: ['', '', '', '']
    },
    {
      id: 7,
      name: 'Tênis New Balance 574',
      category: 'Casual | New Balance | REF:78901234',
      rating: 4.2,
      reviews: 80,
      price: 269.0,
      originalPrice: 350.0,
      installment: 2249.99,
      description: 'O Tênis New Balance 574 é conhecido por seu design clássico e conforto. Ideal para o uso diário com amortecimento e suporte extra.',
      sizes: [39, 40, 41, 42, 43],
      colors: ['#f4a582', '#2ca02c', '#d62728', '#7f7f7f', '#1f77b4'],
      img: 'https://m.media-amazon.com/images/I/611KgyJXPzL._AC_SY695_.jpg',
      thumbnails: ['', '', '', '']
    },
    {
      id: 8,
      name: 'Camisa Asics Performance',
      category: 'Esportiva | Asics | REF:89012345',
      rating: 4.3,
      reviews: 70,
      price: 149.0,
      originalPrice: 220.0,
      installment: 1249.99,
      description: 'A Camisa Asics Performance é perfeita para corredores e atletas com tecnologia que proporciona leveza e ventilação.',
      sizes: ['P', 'M', 'G'],
      colors: ['#e6e6e6', '#ff5722', '#009688', '#3f51b5', '#cddc39'],
      img: 'https://m.media-amazon.com/images/I/71ARX0SJ4rL._AC_SY695_.jpg',
      thumbnails: ['', '', '', '']
    },
    {
      id: 3,
      name: 'Tênis Adidas Ultraboost 22',
      category: 'Performance | Adidas | REF:34567890',
      rating: 4.5,
      reviews: 75,
      price: 349.0,
      originalPrice: 450.0,
      installment: 2929.99,
      description: 'O Tênis Adidas Ultraboost 22 é conhecido pelo seu conforto excepcional e responsividade. Ideal para corrida e treinos intensos, com tecnologia Boost para amortecimento.',
      sizes: [40, 41, 42, 43, 44],
      colors: ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd'],
      img: 'https://m.media-amazon.com/images/I/61MlssKgd-L._AC_SY695_.jpg',
      thumbnails: ['', '', '', '']
    },
    {
      id: 4,
      name: 'Camisa Puma Essentials',
      category: 'Casual | Puma | REF:45678901',
      rating: 4,
      reviews: 60,
      price: 129.0,
      originalPrice: 200.0,
      installment: 1099.99,
      description: 'A Camisa Puma Essentials é perfeita para o uso diário com estilo e conforto. Feita com algodão macio e com o logotipo Puma discreto.',
      sizes: ['P', 'M', 'G'],
      colors: ['#e5e5e5', '#000000', '#ff0050', '#008000', '#0000ff'],
      img: 'https://m.media-amazon.com/images/I/71qePDOt2sL._AC_SY695_.jpg',
      thumbnails: ['', '', '', '']
    },
    {
      id: 5,
      name: 'Tênis Reebok Classic Leather',
      category: 'Casual | Reebok | REF:56789012',
      rating: 4,
      reviews: 85,
      price: 289.0,
      originalPrice: 350.0,
      installment: 2509.99,
      description: 'O Tênis Reebok Classic Leather combina conforto e estilo. Feito com couro premium e solado de borracha para durabilidade e suporte.',
      sizes: [39, 40, 41, 42, 43],
      colors: ['#d62728', '#9467bd', '#8c564b', '#e377c2', '#7f7f7f'],
      img: 'https://m.media-amazon.com/images/I/61MlssKgd-L._AC_SY695_.jpg',
      thumbnails: ['', '', '', '']
    },
    {
      id: 6,
      name: 'Camisa Under Armour Tech',
      category: 'Esportiva | Under Armour | REF:67890123',
      rating: 4.5,
      reviews: 95,
      price: 179.0,
      originalPrice: 250.0,
      installment: 1499.99,
      description: 'A Camisa Under Armour Tech é ideal para atividades físicas com tecnologia que absorve o suor e proporciona uma sensação de frescor.',
      sizes: ['P', 'M', 'G', 'GG'],
      colors: ['#ffcc00', '#00ffcc', '#cc00ff', '#ff3300', '#3399ff'],
      img: 'https://m.media-amazon.com/images/I/71qePDOt2sL._AC_SY695_.jpg_.jpg',
      thumbnails: ['', '', '', '']
    },
    {
      id: 7,
      name: 'Tênis New Balance 574',
      category: 'Casual | New Balance | REF:78901234',
      rating: 4.2,
      reviews: 80,
      price: 269.0,
      originalPrice: 350.0,
      installment: 2249.99,
      description: 'O Tênis New Balance 574 é conhecido por seu design clássico e conforto. Ideal para o uso diário com amortecimento e suporte extra.',
      sizes: [39, 40, 41, 42, 43],
      colors: ['#f4a582', '#2ca02c', '#d62728', '#7f7f7f', '#1f77b4'],
      img: 'https://m.media-amazon.com/images/I/611KgyJXPzL._AC_SY695_.jpg',
      thumbnails: ['', '', '', '']
    },
    {
      id: 8,
      name: 'Camisa Asics Performance',
      category: 'Esportiva | Asics | REF:89012345',
      rating: 4.3,
      reviews: 70,
      price: 149.0,
      originalPrice: 220.0,
      installment: 1249.99,
      description: 'A Camisa Asics Performance é perfeita para corredores e atletas com tecnologia que proporciona leveza e ventilação.',
      sizes: ['P', 'M', 'G'],
      colors: ['#e6e6e6', '#ff5722', '#009688', '#3f51b5', '#cddc39'],
      img: 'https://m.media-amazon.com/images/I/71ARX0SJ4rL._AC_SY695_.jpg',
      thumbnails: ['', '', '', '']
    }
  ];