export const produto = [
  {
    id: 1,
    name: 'Tênis Nike Revolution 6 Next Nature',
    category: 'Casual',
    brand: 'Nike',
    gender: 'Masculino',
    state: 'Novo',
    originalPrice: 350.0,
    rating: 4,
    reviews: 27,
    description: 'O Tênis Masculino Nike Revolution 6 Next Nature revisita o original icônico com linhas de design modernas e amortecimento super leve. O amortecimento Air-Sole revolucionário da Nike foi introduzido nos calçados Nike em 1978.',
    sizes: [39, 40, 41, 42, 43],
    colors: ['#3498db', '#2ecc71', '#e74c3c', '#f39c12', '#9b59b6'],
    img: 'https://m.media-amazon.com/images/I/61KUcjb+paL._AC_SY575_.jpg',
    thumbnails: ['https://m.media-amazon.com/images/I/61KUcjb+paL._AC_SY575_.jpg', 'https://m.media-amazon.com/images/I/61-fXrEPqWL._AC_SY575_.jpg', 'https://m.media-amazon.com/images/I/71vRmCR3ykL._AC_SY575_.jpg'],
    discount: true,
    discountValue: 30
  },
  {
    id: 2,
    name: 'Tênis Nike Dri-FIT Masculina',
    category: 'Esporte',
    brand: 'Nike',
    gender: 'Masculino',
    state: 'Novo',
    originalPrice: 250.0,
    rating: 5,
    reviews: 55,
    description: 'O Tênis Nike Dri-FIT oferece conforto e tecnologia para treinos intensos. Feita com tecido que absorve o suor e mantém você seco, ideal para atividades físicas.',
    sizes: ['38', '39', '40', '41'],
    colors: ['#ff5733', '#33ff57', '#3357ff', '#f4c542', '#a142f4'],
    img: 'https://m.media-amazon.com/images/I/51sIEgkaztL._AC_SX679_.jpg',
    thumbnails: ['https://m.media-amazon.com/images/I/51sIEgkaztL._AC_SX679_.jpg', 'https://m.media-amazon.com/images/I/513aKh4aliL._AC_SX679_.jpg', 'https://m.media-amazon.com/images/I/51iMtyZV3PL._AC_SX679_.jpg'],
    discount: true,
    discountValue: 50
  },
  {
    id: 3,
    name: 'Tênis Adidas Ultraboost 22',
    category: 'Casual',
    brand: 'Adidas',
    gender: 'Unisex',
    state: 'Novo',
    originalPrice: 450.0,
    rating: 5,
    reviews: 78,
    description: 'O Tênis Adidas Ultraboost 22 é conhecido pelo seu conforto excepcional e responsividade. Ideal para corrida e treinos intensos, com tecnologia Boost para amortecimento.',
    sizes: [40, 41, 42, 43, 44],
    colors: ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd'],
    img: 'https://m.media-amazon.com/images/I/51n61hOnQ3L._AC_SX679_.jpg',
    thumbnails: ['https://m.media-amazon.com/images/I/51n61hOnQ3L._AC_SX679_.jpg', 'https://m.media-amazon.com/images/I/51u4P9-AF-L._AC_SX679_.jpg', 'https://m.media-amazon.com/images/I/51weT3D9GKL._AC_SX679_.jpg'],
    discount: true,
    discountValue: 60
  },
  {
    id: 4,
    name: 'Tênis Puma Essentials Master',
    category: 'Casual',
    brand: 'Puma',
    gender: 'Unisex',
    state: 'Novo',
    originalPrice: 200.0,
    rating: 3,
    reviews: 33,
    description: 'O Tênis Puma Essentials é perfeita para o uso diário com estilo e conforto. Feita com algodão macio e com o logotipo Puma discreto.',
    sizes: ['P', 'M', 'G'],
    colors: ['#e5e5e5', '#000000', '#ff0050', '#008000', '#0000ff'],
    img: 'https://m.media-amazon.com/images/I/612e031jM6L._AC_SX679_.jpg',
    thumbnails: ['https://m.media-amazon.com/images/I/612e031jM6L._AC_SX679_.jpg', 'https://m.media-amazon.com/images/I/61+XOCeVRfL._AC_SX679_.jpg', 'https://m.media-amazon.com/images/I/61u9Ry46tqL._AC_SX679_.jpg', 'https://m.media-amazon.com/images/I/518H39CF8VL._AC_SX679_.jpg'],
    discount: false,
    discountValue: 50
  },
  {
    id: 5,
    name: 'Tênis Reebok Classic Leather',
    category: 'Casual',
    brand: 'Reebok',
    gender: 'Unisex',
    state: 'Novo',
    originalPrice: 350.0,
    rating: 4,
    reviews: 22,
    description: 'O Tênis Reebok Classic Leather combina conforto e estilo. Feito com couro premium e solado de borracha para durabilidade e suporte.',
    sizes: [39, 40, 41, 42, 43],
    colors: ['#d62728', '#9467bd', '#8c564b', '#e377c2', '#7f7f7f'],
    img: 'https://m.media-amazon.com/images/I/61In1Kw6cWL._AC_SY575_.jpg',
    thumbnails: ['https://m.media-amazon.com/images/I/61In1Kw6cWL._AC_SY575_.jpg', 'https://m.media-amazon.com/images/I/61lXmqNnmVL._AC_SY575_.jpg', 'https://m.media-amazon.com/images/I/61ru4HQpscL._AC_SY575_.jpg'],
    discount: false,
    discountValue: 0
  },
  {
    id: 6,
    name: 'Tênis Adidas Tech New Balance',
    category: 'Esporte',
    brand: 'Adidas',
    gender: 'Unisex',
    state: 'Novo',
    originalPrice: 250.0,
    rating: 4,
    reviews: 39,
    description: 'O Tênis Adidas Tech é ideal para atividades físicas com tecnologia que absorve o suor e proporciona uma sensação de frescor.',
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['#ffcc00', '#00ffcc', '#cc00ff', '#ff3300', '#3399ff'],
    img: 'https://m.media-amazon.com/images/I/71dRotcBx+L._AC_SY695_.jpg',
    thumbnails: ['https://m.media-amazon.com/images/I/71dRotcBx+L._AC_SY695_.jpg', 'https://m.media-amazon.com/images/I/61zBsmXRoKL._AC_SY575_.jpg', 'https://m.media-amazon.com/images/I/71a1wuejjOL._AC_SY575_.jpg'],
    discount: true,
    discountValue: 30
  },
  {
    id: 7,
    name: 'Tênis Reebok Future Rider',
    category: 'Casual',
    brand: 'Reebok',
    gender: 'Unisex',
    state: 'Novo',
    originalPrice: 350.0,
    rating: 3,
    reviews: 10,
    description: 'O Tênis Reebok Future Rider combina estilo retrô com conforto moderno. Ideal para quem busca um visual despojado e leveza no dia a dia.',
    sizes: [39, 40, 41, 42, 43],
    colors: ['#f4a582', '#2ca02c', '#d62728', '#7f7f7f', '#1f77b4'],
    img: 'https://m.media-amazon.com/images/I/61Ht6pj0JiL._AC_SX675_.jpg',
    thumbnails: ['https://m.media-amazon.com/images/I/61Ht6pj0JiL._AC_SX675_.jpg', 'https://m.media-amazon.com/images/I/71tLhD5U5SL._AC_SX575_.jpg', 'https://m.media-amazon.com/images/I/71JVfLozKkL._AC_SX575_.jpg'],
    discount: false,
    discountValue: 0
  },
  {
    id: 8,
    name: 'Camisa Nike Performance',
    category: 'Esporte',
    brand: 'Nike',
    gender: 'Masculino',
    state: 'Usado',
    originalPrice: 200.0,
    rating: 4,
    reviews: 44,
    description: 'A Camisa Nike Performance é ideal para treinos e atividades físicas, feita com tecido que absorve o suor para manter você seco e confortável.',
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['#ff5722', '#9c27b0', '#cddc39'],
    img: 'https://m.media-amazon.com/images/I/61f8dsHxBFL._AC_SX569_.jpg',
    thumbnails: ['https://m.media-amazon.com/images/I/61f8dsHxBFL._AC_SX569_.jpg', 'https://m.media-amazon.com/images/I/616zAIR1BKL._AC_SX569_.jpg', 'https://m.media-amazon.com/images/I/61fSQbqBOML._AC_SX569_.jpg'],
    discount: true,
    discountValue: 50
  },
  {
    id: 9,
    name: 'Shorts Adidas 3 Listras',
    category: 'Esporte',
    brand: 'Adidas',
    gender: 'Unisex',
    state: 'Novo',
    originalPrice: 180.0,
    rating: 2,
    reviews: 12,
    description: 'Os Shorts Adidas 3 Listras são ideais para treinos e atividades físicas. Feitos com tecido leve e respirável para máximo conforto.',
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['#000000', '#ffffff', '#e57373', '#81c784', '#64b5f6'],
    img: 'https://m.media-amazon.com/images/I/81xR5DygQiL._AC_SX679_.jpg',
    thumbnails: ['https://m.media-amazon.com/images/I/81xR5DygQiL._AC_SX679_.jpg', 'https://m.media-amazon.com/images/I/91SrHs1ihpL._AC_SX679_.jpg', 'https://m.media-amazon.com/images/I/81KDpEQiSHL._AC_SX679_.jpg'],
    discount: false,
    discountValue: 0
  },
  {
    id: 10,
    name: 'Chuteira Nike Mercurial Vapor XIII',
    category: 'Esporte',
    brand: 'Nike',
    gender: 'Unisex',
    state: 'Usado',
    originalPrice: 1100.0,
    rating: 5,
    reviews: 88,
    description: 'A Chuteira Nike Mercurial Vapor XIII oferece velocidade explosiva em campo. Desenvolvida para jogadores que buscam leveza e agilidade.',
    sizes: [38, 39, 40, 41, 42],
    colors: ['#ff2d55', '#5ac8fa', '#4cd964', '#ffcc00', '#5856d6'],
    img: 'https://m.media-amazon.com/images/I/71TJ7RNXvbL._AC_SX675_.jpg',
    thumbnails: ['https://m.media-amazon.com/images/I/71TJ7RNXvbL._AC_SX675_.jpg', 'https://m.media-amazon.com/images/I/71t8Fe4nNIL._AC_SY695_.jpg', 'https://m.media-amazon.com/images/I/71pl8WE5vuL._AC_SX575_.jpg'],
    discount: false,
    discountValue: 0
  },
  {
    id: 11,
    name: 'Regata Nike Sportstyle',
    category: 'Esporte',
    brand: 'Nike',
    gender: 'Unisex',
    state: 'Novo',
    originalPrice: 150.0,
    rating: 4,
    reviews: 19,
    description: 'A Regata Nike Sportstyle proporciona conforto e mobilidade durante os treinos. Ideal para dias quentes e atividades ao ar livre.',
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['#00bcd4', '#ff4081', '#8bc34a', '#ff9800', '#9c27b0'],
    img: 'https://m.media-amazon.com/images/I/61He4sTUIHL._AC_SX679_.jpg',
    thumbnails: ['https://m.media-amazon.com/images/I/61He4sTUIHL._AC_SX679_.jpg', 'https://m.media-amazon.com/images/I/61aEzLXHSsL._AC_SX569_.jpg', 'https://m.media-amazon.com/images/I/61gN20VZKUL._AC_SX569_.jpg'],
    discount: true,
    discountValue: 60
  },
  {
    id: 12,
    name: 'Tênis Puma Future Rider',
    category: 'Casual',
    brand: 'Puma',
    gender: 'Unisex',
    state: 'Usado',
    originalPrice: 300.0,
    rating: 3,
    reviews: 34,
    description: 'O Tênis Puma Future Rider combina estilo retrô com conforto moderno. Ideal para quem busca um visual despojado e leveza no dia a dia.',
    sizes: [39, 40, 41, 42, 43],
    colors: ['#ffcc00', '#00ffcc', '#ff6600', '#cc00ff', '#99cc00'],
    img: 'https://m.media-amazon.com/images/I/71fDJtKqrnL._AC_SX675_.jpg',
    thumbnails: ['https://m.media-amazon.com/images/I/71fDJtKqrnL._AC_SX675_.jpg', 'https://m.media-amazon.com/images/I/71a7m1ZQdrL._AC_SX575_.jpg', 'https://m.media-amazon.com/images/I/71vmxuU-6jL._AC_SX575_.jpg'],
    discount: true,
    discountValue: 80
  }
  ];
  